### ISSUE TITLE
Blinking

### ISSUE THREAD

**Issue by SergeyNZ** [TurboPack/SynEdit#1]
Can you make so that the component does not blink when I selecting text or moving the cursor
Thank you

**Comment by romankassebaum** [comment]
Do you have a small demo app?

**Comment by SergeyNZ** [comment]
-------------------------------------------------------------------
MDaemon has detected restricted attachments within an email message
-------------------------------------------------------------------

From      : sergey@ipotekabank.com
To        : reply@reply.github.com
Subject   : Re: [SynEdit] Blinking (#1)
Message-ID: <B731BC41F75E49EEA703A5BE9D24DDA5@sergey1>

---------------------
Attachment(s) removed
---------------------
TestProjSynEdit.zip (Project2.exe)

**Comment by SergeyNZ** [comment]
This project for XE4(for XE8 I can send tomorrow but this problem is remained)

Try to select text with the mouse or move cursor using keyboard and you see this

Thank you

**Comment by romankassebaum** [comment]
The demo app for XE4 would be enough but you must remove the binaries before you send the zip archive, otherwise it will be removed.

**Comment by SergeyNZ** [comment]
Try to select text with the mouse or move cursor using keyboard and you see this

Thank you

**Comment by SergeyNZ** [comment]
Have you received demo app in last letter?

**Comment by romankassebaum** [comment]
I still have no demo app.

**Comment by SergeyNZ** [comment]
Tell me your email which I can send

**Comment by SergeyNZ** [comment]
Add  please  
property ActiveLineColor; 
in TDBSynEdit
Thank you

**Comment by romankassebaum** [comment]
I added the ActiveLineColor but I have no idea how to stop the blinking cursor. And all editors have a blinking cursor.
