### ISSUE TITLE
Is it possible for FMX?

### ISSUE THREAD

**Issue by dtamade** [TurboPack/SynEdit#10]
Is it possible for FMX?
What time?

**Comment by romankassebaum** [comment]
I guess it is but not for free. :-)

**Comment by Kashaket** [comment]
> Is it possible for FMX?
> What time?

Just try porting it to the LCL (Lazarus), you'll achieve maybe not the best interface experience, but save a lot of time

**Comment by pyscripter** [comment]
Porting Synedit to FMX or Lazarus is outside the scope of this repository (at least for the near future).

**Comment by JakesFouche** [comment]
An FMX version of this would really be amazing!

**Comment by shaunroselt** [comment]
Maybe wrapping Monaco Editor into a component for an FMX version?

https://github.com/microsoft/monaco-editor

This should be a faster and an easy short-term solution to get SynEdit onto FMX.

Monaco is great too. This would be great for many people.

**Comment by Vizit0r** [comment]
> Maybe wrapping Monaco Editor into a component for an FMX (FireMonkey) version?

what does it mean "wrapping" ?
There are no any kind of wraps, just rewrriting.

**Comment by shaunroselt** [comment]
> > Maybe wrapping Monaco Editor into a component for an FMX (FireMonkey) version?
> 
> what does it mean "wrapping" ? There are no any kind of wraps, just rewrriting.

Basically whatever they did here: https://www.tmssoftware.com/site/tmsfncuipack-memo.asp

**Comment by Vizit0r** [comment]
> Basically whatever they did here: https://www.tmssoftware.com/site/tmsfncuipack-memo.asp
until i will see in their source - i will continue to say "no any "wraps" available. There are not possible to put all this to Lib, and than  call some methods.

My opinion - they do big job and rewrite it fully.

**Comment by shaunroselt** [comment]
I found a video showing it and explaining how it's built and how it works:

https://youtu.be/IojHrnBurZU?si=D9EE5tCNkgFci-En
