### ISSUE TITLE
Assert message and issues deleting word wrapped lines with gutter showing line numbers.

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#102]
There seems to be an issue with selecting and deleting word wrapped lines if the gutter is set to show line numbers.  An easy way to see the message is to open a file with word wrapped lines (my test file is 100 lines of about 200 characters each.   A standard sentence with words and spaces btw.),  Size the window if needed so that the lines are wrapping.  Select all, and hit delete.  You should see the message:

Project SynEditTest.exe raised exception class EAssertionFailed with message 'Assertion failure (...SynEditWordWrap.pas, line 269)'.

If you do smaller deletes they will work-ish, though the gutter line numbers get out of synch with the actual text (extra number lines at the end on the gutter that don't exist in the editor.)

Let me know if you need more info or testing on this.  Thanks!!

**Comment by pyscripter** [comment]
I am not able to reproduce this one.

![image](https://user-images.githubusercontent.com/1311616/142723611-4b96ff4b-0f9b-4eaa-82f8-5519400b48b2.png)

Deleting all lines or deleting a few lines works as expected here.

**Comment by MShark67** [comment]
Found it!  The missing piece of the mystery is that it only happens if the gutter width changes during the delete.  In my test I had the Gutter DigitCount set to 2, so I see the error at 100 lines.  If it's set to 4 (the default I think) you won't see it until 10,000 lines.  Here's some sample code that causes it every time.   I think it has something to do with SetGutterWidth calling the Wrap plugin DisplayChanged /Reset method during the delete.

  SynEdit1.Gutter.ShowLineNumbers := True;
  SynEdit1.Gutter.DigitCount := 2;
  SynEdit1.WordWrap := True;

  var S :=
    '%d: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ' +
    'tempor incididunt ut labore et dolore magna aliqua. Enim neque volutpat ' +
    'ac tincidunt vitae semper quis. Pellentesque habitant morbi tristique ' +
    'senectus et netus.';

  // Fill the Edit with 100+ lines.
  for var i := 1 to 101 do
    SynEdit1.Lines.Add(Format(S, [i]));

  // Now select and delete which should cause the assert error.
  SynEdit1.SelectAll;
  SynEdit1.SelText := '';

**Comment by pyscripter** [comment]
Thanks! I can now reproduce it.
