### ISSUE TITLE
Issue with backspace at CaretX = 1 of a line.

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#103]
Currently if you backspace at the first char of a line, the caret will jump to the end of the current line instead of the line above.  The fix is:

SynEdit.pas line: 6278

Old line:
CaretXY := BufferCoord(Lines[CaretY - 1].Length + 1, CaretY - 1);

Fix line:
CaretXY := BufferCoord(Lines[CaretY - 2].Length + 1, CaretY - 1);

-Mark

**Comment by pyscripter** [comment]
Thanks for the report and the solution!  Keep it up...
