### ISSUE TITLE
Can't compile in Delphi 10.1 Berlin

### ISSUE THREAD

**Issue by erichkuba** [TurboPack/SynEdit#104]
Hi there,

I'm trying to compile and install the package Delphi 10.1 Berlin, but there seem to be many errors.  I am aware that I can install the packages via GetIt and that works, but I'm not sure how old that code is and I wanted the latest version.  The project says that it supports Berlin and up, so I must be doing something wrong. Any input would be valued.

Kind regards

Erich

**Comment by pyscripter** [comment]
Don't have Berlin installed (never had), so I cannot help.   The Turbo project aims to support the latest version of Delphi.  Look at the releases for versions supporting earlier versions of Delphi such as Berlin.

Having said that, if the changes required to support Berlin in the master branch are not many, I would consider merging them.
