### ISSUE TITLE
Can't compile current master branch in Delphi 10.1 Berlin

### ISSUE THREAD

**Issue by BorisU7** [TurboPack/SynEdit#105]
[dcc32 Error] SynEditTextBuffer.pas(521): E2003 Undeclared identifier: 'GrowCollection'
[dcc32 Error] SynEditTextBuffer.pas(568): E2003 Undeclared identifier: 'GrowCollection'
[dcc32 Fatal Error] SynUnicode.pas(1936): F2063 Could not compile used unit 'SynEditTextBuffer.pas'

As far as I can see GrowCollection function was introduced in Delphi 10.3 Rio. Funny enough release 103RIO compiles just fine

**Comment by pyscripter** [comment]
This is how GrowCollection is defined.

```pascal
function GrowCollection(OldCapacity, NewCount: Integer): Integer;
begin
  Result := OldCapacity;
  repeat
    if Result > 64 then
      Result := (Result * 3) div 2
    else
      if Result > 8 then
        Result := Result + 16
      else
        Result := Result + 4;
    if Result < 0 then
      OutOfMemoryError;
  until Result >= NewCount;
end;
```

You can add it to SynEditMiscProcs with IFDEF and if you want submit a PR.

**Comment by BorisU7** [comment]
I made a fix with conditional compilation for  10.1 for this and an pair of other issues. Now I need to learn how I create a PR :)

**Comment by pyscripter** [comment]
Fixed in #106

**Comment by pyscripter** [comment]
Thx!

**Comment by BorisU7** [comment]
I suppose #104 is also fixed
