### ISSUE TITLE
Ctrl+BackSpace behavior

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#107]
User reported me change of Ctrl+BkSpace behavior.
Current behavior - when cursor stays on the end of word, after Ctrl+BkSpace Synedit deletes it to the end of the word. If there is any char (space, bracket) before cursr, it doesn't do anything.

Delphi IDE and previous Synedit behavior - you can stay anywhere and everything to the begin of start of the word from the current cursor position is deleted.

Example (| is cursor position) when you repeatedly pres Ctrl+BkSpace (test it in Delphi IDE):
```
Size := Stream.Size - Stream.Position;  |
Size := Stream.Size - Stream.|
Size := Stream.Size -|
Size := Stream.|
....

```

**Comment by JaFi-cz** [comment]
Synedit calls WordStart() what calls TCustomSynEdit.WordStartEx()
But WordStartEx returns start of the word only if cursor stays on the end of word.

Something like this should be used in the ecDeleteLastWord comand:
```
wp := WordStart;
if CaretXY = wp then
begin
  wp := PreviousWordEnd;  // non existing function yet
  wp := WordStart;
end;
```

**Comment by JaFi-cz** [comment]
I know I can override WordStart in my descendant in Synedit to something like function derived from WordStartEx(). I added 3 lines:
```
    // find the end of the word
    if IsWordBreakChar(Line[CX - 1]) then
      CX := StrRScanForCharInCategory(Line, CX - 1, IsIdentChar) + 1;
```

```
function TPSSynEdit.WordStart: TBufferCoord;
var
  XY: TBufferCoord;
  CX, CY: Integer;
  Line: string;
begin
  XY := CaretXY;
  CX := XY.Char;
  CY := XY.Line;
  // valid line?
  if (CY >= 1) and (CY <= Lines.Count) then
  begin
    Line := Lines[CY - 1];
    CX := Min(CX, Length(Line) + 1);
    // find the end of the word
    if IsWordBreakChar(Line[CX - 1]) then
      CX := StrRScanForCharInCategory(Line, CX - 1, IsIdentChar) + 1;

    if CX > 1 then
    begin
      // only find previous char, if not already on start of line
      // if previous char isn't a word-break-char search for the last IdentChar
      if not IsWordBreakChar(Line[CX - 1]) then
        CX := StrRScanForCharInCategory(Line, CX - 1, IsWordBreakChar) + 1;
    end;
  end;
  Result.Char := CX;
  Result.Line := CY;
end;

```

**Comment by pyscripter** [comment]
Isn't it better to include these three lines to the handling of ecDeleteLastWord and leave WordStart alone?

**Comment by JaFi-cz** [comment]
Of course the best way is to fix ecDeleteLastWord command. My solution is workarround till it will be fixed. BTW WordStart is used in the ecDeleteLastWord only.

**Comment by JaFi-cz** [comment]
Pull request with ecDeleteLastWord and ecDeleteWord commands created
