### ISSUE TITLE
GetMatchingBracketEx for additional characters

### ISSUE THREAD

**Issue by aehimself** [TurboPack/SynEdit#109]
Hello,

Based on the code [here](https://stackoverflow.com/questions/18487553/synedit-onpainttransientdemo) I want to implement a Delphi-like highlighting which includes single and double quotes as well.
This code relies on GetMatchingBracketEx, which is not going to work as the symbols to be matched are stored as a constant.

I know that the method is virtual and can be overridden (or simply copied from SynEdit to an external method) but this kind of code duplication is unwanted.

A new method could be implemented, called GetMatchingCharacter, which includes the search logic and takes the array as parameter. This way extending would be easy and could be done without redundancy and keeping current functionality intact.

Any thoughts?

**Comment by pyscripter** [comment]
GetMatchingBracketEx is now declared as: 

```pascal
   function GetMatchingBracketEx(const APoint: TBufferCoord;
      Brackets: string = '()[]{}<>'): TBufferCoord; virtual;

```
