### ISSUE TITLE
Minor fix for DeleteLastWord with Caret at char 1 on a line.

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#111]
Pressing Ctrl-Backspace with the caret at position 1 on a line causes an AV.  It just needs a WP.Char > 1 test like so:

SynEdit.Pas line 6469:
            if (WP.Char > 1) and IsWordBreakChar(LineText[WP.Char - 1]) then

-Mark

**Comment by pyscripter** [comment]
You are not using the latest version.   I cannot reproduce with the current version.

**Comment by MShark67** [comment]
The line number I gave is incorrect.  The actual line is 6449.  Sorry about that.  Other than that I *think* I'm up to date.  I double checked the SynEdit.pas file in this repos and the LineText[WP.Char - 1] which is the crux of the problem is definitely in there without an index check.  Run with debug mode and range checking on since the AV can be spotty.  A Ctrl-Backspace on an empty file should do it, as well as any Ctrl-Backspace with the caret at char 1.
