### ISSUE TITLE
ecSelDown, ecSelPgDown, ecSelUp, ecSelPgUp, Autoindent behavior

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#115]
When you select lines with Shift+Down or Shift+PgDown, the last line isn't selected
simulation file content:
```
line1
line2
```
simulation instruction:
put cursor on the 1,1 position, pres 2x Shift+Down. Last line should be selected too

**Comment by pyscripter** [comment]
Notepad and the Delphi IDE behave as SynEdit.
On the other hand, VS code moves the cursor to the end of the current line when you are at the last line.

This is not just about Shift-Down and Shift-PgDown.  One needs to be consistent.
In VS Code Down, Up Shift+Up  also behave in an analogous manner.  

I will accept a PR that deals with all such cases.

**Comment by JaFi-cz** [comment]
OK, added change for ecSelPgUp, ecSelUp too

Added fix for Autoindent.
Simulation (some text starting with spaces or tabs, followed by empty line and cursor on the start of next line):
```
      some text
¶
|¶
```

When you press enter, spaces from first line are added even you stay on the begin of line

**Comment by pyscripter** [comment]
Up, Down, PgUp, PgDown should also behave similarly.   Check with VS Code or Word.

lin^e1

if you press Up or PgUp

^line1


line^last

if you press Down or PgDn

linelast^

**Comment by JaFi-cz** [comment]
But it's already done together with ecSelUp e.t.c. In this case it only changes caret position

**Comment by JaFi-cz** [comment]
So will you accept it? ecUp, ecPgUp, ecDown and ecPgDown behavior is already included in previous modification

**Comment by pyscripter** [comment]
Yes I will.  I just want to check first.
