### ISSUE TITLE
Adding unwanted line breaks

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#117]
Synedit adds unwanted line break when you save to stream.
Even Lines.TrailingLineBreak := True;

Simulation:
New empty VCL application and put following code to form create

```
procedure TForm1.FormCreate(Sender: TObject);
var
  ms: TMemoryStream;
begin
  ms := TMemoryStream.Create;
  with TSynedit.Create(self) do
  begin
    Parent := Self;
    Align := alClient;
    Options := Options + [eoShowSpecialChars];
    { now we add 2 lines}
    Lines.Clear;
    Lines.Add('Test line');
    Lines.Add('');
    { 1 save to stream / Load from stream - adds one additional line break }
    ms.Clear;
    Lines.SaveToStream(ms);
    ms.Position := 0;
    Lines.LoadFromStream(ms);

    { 2 save to stream / Load from stream - adds one additional line break }
    ms.Clear;
    Lines.SaveToStream(ms);
    ms.Position := 0;
    Lines.LoadFromStream(ms);
  end;
end;
```

Problem is in the SyneditTextBuffer.PAS
procedure TSynEditStringList.SaveToStream()
this code adds unwanted line break
    S := GetTextStr;

FIX:
```
    S := GetTextStr;
    { when strings.TrailingLineBreak then cut off last CrLf }
    if TrailingLineBreak then
      SetLength(s, Length(s) - Length(LineBreak));

```

**Comment by pyscripter** [comment]
> Even Lines.TrailingLineBreak := True;

Do you mean False?

**Comment by pyscripter** [comment]
GetTextStr is inherited and works fine.  The problem is in SetTextAndFileFormat.

```pascal
      // keep the old format of the file
      if not TrailingLineBreak and (CharInSet(Value[Size], [#10, #13]) or
        (Value[Size] = WideLineSeparator)) then
        InsertItem(FCount, '');
```

Could you please remove the not and test whether it behaves correctly?

**Comment by pyscripter** [comment]
Actually I got it all wrong.

Forget about the above.   The only change needed is to change in SetTextAndFileFormat

```pascal
      while (P <= Pmax) do
      begin
        Start := P;
```
the first line above to 

```pascal
      while (P < Pmax) do
```

Then the file is preserved when saving and loading whether TrailingLineBreak is True or False.

Could you please check this change?

**Comment by JaFi-cz** [comment]
The last modification fixes it.
