### ISSUE TITLE
WordWrap with Right edge

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#124]
In my version I use WordWrap with Right Edge line, not only with windows width.
Settings is via Synedit option.
Do you think it can be usefull for the others too?

It allows you to dynamically change and see see wrapped text result for different width, in my case by clicking on the top ruller. 

There is no much changes in code, it's necessary to handle CharsInWindow in SynEditWordWrap.pas and extend reaction on Right Edge change in the Synedit.pas.

**Comment by pyscripter** [comment]
Yes it could be useful.
