### ISSUE TITLE
Rendering error when resizing a form

### ISSUE THREAD

**Issue by Ta2i4** [TurboPack/SynEdit#129]
![bug](https://user-images.githubusercontent.com/63456473/148146836-0a20cb41-a230-4e9f-bd71-4375a244a815.png)

If the Align property of the TSynEdit component is set to the value alRight, then when the WindowState property is changed to wsMaximized in the TForm component, a rendering error of the TSynEdit component appears.

This error can be fixed by using the code in the TForm.OnResize event:
`SynEdit1.Repaint;`

Tested on: Delphi 10.4.2 Sydney Community Edition, operating system MS Windows 11 (21H2).

Delphi project for example:
[test.zip](https://github.com/TurboPack/SynEdit/files/7811495/test.zip)

**Comment by pyscripter** [comment]
I cannot reproduce with the current state of the project.  
Please sync your SynEdit with the master branch of this repo and test again.

It could be that the fix to #96 fixes this one as well.

**Comment by Ta2i4** [comment]
Yes, fix in #96 fixes this one. Thanks!
