### ISSUE TITLE
MDI Application

### ISSUE THREAD

**Issue by ghost** [TurboPack/SynEdit#13]
When using SynEdit in MDI application with TSynCompletentionProposal, when it unfocuses, it sends focus to the previous MDI form, but not to the parent control, which is quite annoying with floating controls/forms

Nevertheless, thanks for so useful project

**Comment by pyscripter** [comment]
Please submit a small test application that reproduces the issue.

**Comment by uhjiok123** [comment]
Hello，
【The following English languages are from Google Translate】
I think I also got this error，
In my MDI form, this error also appeared,
When I use the PageControl, when I close the tab(Page), SynEdit will be Destory, but the Destory sequence is wrong:
See my screenshot:
[<a href="https://ibb.co/wY318fH"><img src="https://i.ibb.co/g6HCQx1/Synedit-Destory-Err.jpg" alt="Synedit-Destory-Err" border="0"></a>](url)
The picture on the left is from TurboPack/SynEdit,
When you reach this step :  inherited Destroy; (Line 35) ,FKbdHandler has been Free once,
This will result in fKbdHandler = nil --> Access Violation ... error will occur,
[<a href="https://imgbb.com/"><img src="https://i.ibb.co/wdFgGLM/Synedit-Destory-Err2.jpg" alt="Synedit-Destory-Err2" border="0"></a>](url)
Eventually the focus cannot be transferred to the Parent .
But when I adjust the order, these things will not happen,just like the picture on the right;

**Comment by pyscripter** [comment]
I see...
Will fix it soon.

**Comment by pyscripter** [comment]
@uhjiok123 Fixed.
Please open a new issue next time.  This was unrelated to to the current issue.
