### ISSUE TITLE
Issue with ecDown or ecSelDown with wordwrap on and a wrapped final line.

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#131]
If wordwrap is on and the final line of the SynEditor is wrapped, then pressing the down arrow key moves to the end of the "first line of the wrapped line" and further down presses won't move the caret downwards to the lower wrapped lines.  My quick fix is below, but I'm guessing there's a way to get it to work correctly regardless of wrapping.

```
      ecDown, ecSelDown:
        begin
          if not WordWrap and (CaretY = Lines.Count) then
          begin
            SaveLastCaretX := fLastCaretX;
            DoEndKey(Command = ecSelDown);
            fLastCaretX := SaveLastCaretX;
          end
          else
            MoveCaretVert(1, Command = ecSelDown);
          Update;
        end;
```
-Mark

**Comment by pyscripter** [comment]
Does this work?

`if (WordWrap and (DisplayY = fWordWrapPlugin.RowCount) ) or (CaretY = Lines.Count) then`

**Comment by pyscripter** [comment]
Could you please submit a PR?

**Comment by MShark67** [comment]
Yes, absolutely.  I have some setup to do, so it may take a day or so.  I've been meaning to do that in any case.  Thanks

**Comment by MShark67** [comment]
Turns out the issue also affects PageUp and PageDown so I made those changes as well.
