### ISSUE TITLE
Copy to Clipboard (HTML Revisit)

### ISSUE THREAD

**Issue by sllimv1973** [TurboPack/SynEdit#137]
So I recently ran into the issue you fixed in issue #70.  But there is at least one other issue with the copy HTML format that I think needs to be addressed.  When the HTML copy was working there was an additional word prepended to the HTML block that wasn't apart of my original text.  the word was "untitled". Due to the way HTMLExport works it expects that the user will provide a value in the Title property of TSynExporterHTML.  This shouldn't normally be an issue but Google Mail when you paste the block fills in the untitled title with "untitled".

The way I fixed it was with the following code in TSynExporterHTML:
`  if not fCreateHTMLFragment then `
`    Header := Header + '<title>' + Title + '</title>'; `
`  Header := Header + #13#10 + `
`    Format(HTMLAsTextHeader2, [EncodingStr, ColorToHtml(fFont.Color), `
`      ColorToHTML(fBackgroundColor), Styles]); `

As a side note, I think the better fix for the HTML vs Pain Text copy option is to make the new option eoCopyHTMLText rather than eoCopyPlainText. I would suspect that most people would prefer to opt in to the HTML copy than to opt in to plain text.

**Comment by pyscripter** [comment]
Thanks for this.  Is it possible to submit a PR?  

Currently the default is to include both Plain Text and HTML in the DataObject (used for copying and dragging).  With eoCopyPlainText  the HTML is left out. 

If both formats are included then the application you copy/drag to selects the preferred option.

**Comment by sllimv1973** [comment]
My current version is heavily modified from your version. I can try and isolate for a PR but it's not going to be simple.
As to the default....it wasn't the default for a very long time and since this is now in the Delphi GetIt repository, more people will come across this behavior and find it counter intuitive and backwards.  Normally this type of thing should be provided as an additional feature rather than an unexpected feature.  As was noted in the original #70 issue, the behavior was not what was expected and the developers customers suddenly started getting things that they were not expecting.  That would be considered a breaking change for anyone who would now be upgrading their SynEdit to what is easily available in the GetIt repository. This direction would then lend itself to also supporting RTF in a similar mannor,  eoCopyRTFText, for example.

**Comment by pyscripter** [comment]
Allow me to disagree.  This is the default for example in VS Code.  When you move text to other applications by copying or dragging, you offer a choice of formats and let the other application choose the formal.  Additional formats could be offered as for example RTF, but nowadays most applications given a choice between HTML and RTF would prefer HTML.

You don't like that.  Then just use the eoCopyPlainText to simulate old behavior.

In any case, the overall aim is to modernize SynEdit and bring it out of the dark ages, even if that means sometimes breaking backward compatibility.  Just look at the [enchancements](https://github.com/TurboPack/SynEdit/issues?q=is%3Aissue+label%3Aenhancement+) scheduled or planned

**Comment by sllimv1973** [comment]
Modernizing something doesn't mean that you have to break things that already work. Introducing new functionality on top of existing functionality that causes things to happen, or break, unexpectedly for someone else is something that I as a component developer try to avoid. By providing it as an option that can be turned on by the end developer you can still "bring it out of the dark ages" with out making someone else look bad. That's my opinion. I'm sorry you don't feel that way as well.
