### ISSUE TITLE
SynComplete autosize flickering

### ISSUE THREAD

**Issue by ghost** [TurboPack/SynEdit#14]
Delphi 101Berlin
![image](https://user-images.githubusercontent.com/22324695/54203916-d561e500-44db-11e9-925e-c0bbfc7eed87.png)
(and so on, out of screen)

**Comment by pyscripter** [comment]
What do you mean by autosize?
Please submit a minimal test project that replicates the issue.

**Comment by pyscripter** [comment]
Close since there is no feedback.
