### ISSUE TITLE
SynGutter ShowLineNumbers

### ISSUE THREAD

**Issue by groehner** [TurboPack/SynEdit#148]
In SynEditMiscClasses.pas procedure TSynGutter.Assign(Source: TPersistent);

 FShowLineNumbers := Src.ShowLineNumbers;    is missing.

It's initalization in TSynGutter.Create is implicit, not
explicit like most other attributes.

**Comment by pyscripter** [comment]
Fixed in the DWrite branch that will be merged with the master soon.
