### ISSUE TITLE
Can't compile new version with Delphi 10.2 Tokyo

### ISSUE THREAD

**Issue by khongten001** [TurboPack/SynEdit#155]
Hi all,

Thank you for making this release! As the title, I can't compile the new version with Delphi Tokyo! Is there any chance to support Delphi Tokyo?

Thank you!

**Comment by pyscripter** [comment]
By all means, but you need to tell us what fails to compile of even better, make it compile and submit a PR.

**Comment by BorisU7** [comment]
Same here with Delphi 10.1 Berlin. 

As I can see new code uses things that are not present in earlier Delphi versions ;(

```
function DWGetTypography(Features: array of Integer) : IDWriteTypography;
begin
  CheckOSError(TSynDWrite.DWriteFactory.CreateTypography(Result));
  for var Feature in Features do
    CheckOSError(Result.AddFontFeature(DWFontFeature(Feature, 1)));
end;
```
uses syntax that appeared in 10.3 

constant DWRITE_WORD_WRAPPING_EMERGENCY_BREAK is present in Delphi 10.4 and 11 but absent in 10.1

**Comment by BorisU7** [comment]
I made it compiling in 10.1 with some fixes but got the following error at runtime. Have no idea what does it mean.

![image](https://user-images.githubusercontent.com/17879557/152644050-0d159040-c6a2-4c92-b458-7e9437ddccc2.png)

**Comment by MShark67** [comment]
Could this have something to do with [this bug that was fixed in 10.4 ](https://quality.embarcadero.com/browse/RSP-26621)?  I'm no expert on this but I had remembered reading about it in [this praxis thread.](https://en.delphipraxis.net/topic/4358-32bit-bitmap/)

**Comment by BorisU7** [comment]
After I disabled the gutter in my project it seems working in 10.1

**Comment by pyscripter** [comment]
@MShark67 This is a good guess.  I see what I can do.
@BorisU7 Could you please share with us the changes that are required to compile with 10.1?

**Comment by BorisU7** [comment]
I submitted a PR.

**Comment by pyscripter** [comment]
@Boris Have you tried the updates?  Does the gutter now show?

**Comment by BorisU7** [comment]
Yes. gutter is now fine, though I didn't test very thoroughly. My patch is made against your corrected version.

**Comment by pyscripter** [comment]
Your PR is committed.  I have also replaced the unsupported class destructor.

**Comment by pyscripter** [comment]
Should now be fixed.  See the last couple of commits.
