### ISSUE TITLE
Crash when setting a highlighter on a very wide text file (over 65536 chars wide)

### ISSUE THREAD

**Issue by DGH2112** [TurboPack/SynEdit#159]
Hi,
I've been trying to swap over from SynEdit\SynEdit to TurboPack\SynEdit and have found one issue when opening one type of file I use which has very wide lines (over 65536 characters). I believe I've isolated it to the following portion of code where `CeilOfIntDiv()` is called. That function returns a `Word` whereas the `MaxScroll` and other variables are integers. In my example file, `MaxWidth` returns a value greater than 65536. These are unusually large files but I do have to edit them on occasions and use my own editor based on SynEdit (32 and 64-bit as these can be in the 100MB size range).

```
procedure TSynEditScrollBars.UpdateScrollBarsState;
...
begin
  ...
      MaxScroll :=
        (CeilOfIntDiv(TSynEditStringList(FOwner.Lines).MaxWidth,
        FOwner.CharWidth)  + 1) * FOwner.CharWidth;
  ...
```

Apologies, I didn't setup a fork, I just cloned the repository into my app. The RTL does not seem to have an alternative for `CeilOfIntDiv()` which works with Integers or cardinals.
regards
Dave.

**Comment by DGH2112** [comment]
Sorry, I should have said the underlying `DivMod()` in `CeilOfIntDiv()` does have an alternative in the RTL for integers/cardinals.

**Comment by pyscripter** [comment]
Could you please test again.

**Comment by DGH2112** [comment]
@pyscripter  Yes, that fixed works thank you.
regards
Dave.
