### ISSUE TITLE
Long lines fix

### ISSUE THREAD

**Issue by BorisU7** [TurboPack/SynEdit#166]
#161 fix seems to break my usage of SynEdit. Not now, cause I am currently at Delphi 10.1 and the fix is disabled, but probably in the future if I upgrade. I am using SynEdit to display the tabular data generated by the program and lines can potentially be very long. As far as I understand the fix it forcibly turns on Wordwrap if finds a line longer than 10000.  This will break the table formatting for me. I understand that my case is rare so I propose to leave the behavior as is if it really speeds up the loading. All I need is a possibility to disable this fix with some flag, or maybe make 10000 a variable and allow 0 to disable the feature.

Also a minor issue: in 10.1 I get a warning from a compiler on unused variable 'I' cause the code using it is disabled in 10.1.

**Comment by MShark67** [comment]
I agree.  I'd either vote for removing the feature for now or adding an integer property like RightEdge but called something like AutoWrapEdge with a default of zero.  I think that Boris is right about the type of file it would happen on and how that type of file doesn't work at all when wrapped.

**Comment by pyscripter** [comment]
But you can always manually set WordWrap = False after the file is loaded.   This is what VS Code does.

**Comment by pyscripter** [comment]
"Fix" removed.
