### ISSUE TITLE
CaseSensivity

### ISSUE THREAD

**Issue by jeancremers** [TurboPack/SynEdit#17]
Please please add case sensivity, i can't port my project without it, i'd have to change language features. I have a 630 lines long msg file with lots of tokens.

**Comment by pyscripter** [comment]
The above is very unclear.  What should be case sensitive?

**Comment by pyscripter** [comment]
I have no clue what the issue. is  SynEdit is an editor and you can have both 'button' and 'BUTTON' in the text.

**Comment by jeancremers** [comment]
I'm talking about the syntax  highlighter.

**Comment by pyscripter** [comment]
Which syntax highlighter? For example python and others are case sensitive.  There is no restriction about whether the highligher is case sensitive or not.

**Comment by jeancremers** [comment]
i have my own language, using a 600+ lines .msg file. I could not get case sensivity to work, i tried for hours hacking in the source. I don't remember it very well because it's some months ago but i kept getting errors as soon as i tried the same word in different case.

**Comment by pyscripter** [comment]
Did you use an existing hightlighter or did you write your own?

When you create an issue please submit a minimal test project that reproduces the issue.
Otherwise you make it very hard for anyone to provide help.

**Comment by jeancremers** [comment]
I made my own with help from the author of PsPad many years ago, using an older version of synedit for c++builder 6. It was rather complicated also because the file that was generated did not compile, my .msg was too big and i had to embed syngen in an app of my own that would modify the .pas after syngen was done.
Take a look, lot of words that only differ in case.
[Astrobasic.msg.txt](https://github.com/TurboPack/SynEdit/files/5184390/Astrobasic.msg.txt)

I'm not sure how to proceed here. 
A minimal test project using two same keywords in different case would be an idea yes.
