### ISSUE TITLE
Language and friendly names of SynHighlighterDWS.

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#173]
Currently this highlighter uses "ObjectPascal" and "Object Pascal" respectively, which is also used for the SynHighlighterPas highlighter. 
Should they be changed to something more specific?  "DWScript Pascal" or such?

**Comment by MShark67** [comment]
Just a note that this highlighter needs {$Q-} and {$Q+} added around its HashKey function.

**Comment by pyscripter** [comment]
Agree.  Also There were some updates to this highlighter on SynEdit\SynEdit.   Could you please have a look and submit a PR?
Thanks.
