### ISSUE TITLE
Bug in height calculation

### ISSUE THREAD

**Issue by mair0301** [TurboPack/SynEdit#18]
Good morning,
In our software projects we are using your TSynCompletionProposal component for auto syntax completion. After using that for a while, we determined a little bug in this component. Whenever the popup window of the TSynCompletionProposal component appears (through a keyboard shortcut), the height of this component is increased. After appearing five to six times, this component is as high as the screen.
 
We’ve tried to solve the problem by developing our own solution, but didn’t have any real success. After hours of debugging, we guess that the CanResize, Paint and AdjustMetrics methods are responsible for that behavior.
 
So I kindly ask you to fix this problem or provide us with a suitable solution.
Best regards from Germany 😊

**Comment by romankassebaum** [comment]
I just merged SynEdit with the version from pyscripter. Is the issue still there?

**Comment by mair0301** [comment]
Now we’ve tried the latest version of the SynEdit, but the bug is still there.  Whenever the proposal appears, the height is increased. Can you please fix this?

**Comment by pyscripter** [comment]
I will have a look.   I am using a different version of TCompletionProposal, so it has not received all the bug fixes I have made.
