### ISSUE TITLE
Rename .groupproj to something usefull

### ISSUE THREAD

**Issue by Bascy** [TurboPack/SynEdit#2]
Please rename the .groupproj file into SynEdit_Delphi.groupproj so the file is identifiable part of Synedit package

**Comment by romankassebaum** [comment]
The problem could be that the project group will be automatically opened during installation process via GetIt. Maybe Marco could say more.

**Comment by Bascy** [comment]
Other packages like omnithread have different group names afaik
Op 13 okt. 2015 17:19 schreef "Roman Kassebaum" <notifications@github.com>:
