### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#201]
The only Windows 7 machine I have is an old laptop with Windows 7 with SP1, but no other updates.  In testing the new SynEdit I don't see any text drawn (including line numbers in the gutter.)  The caret position is shown and the scroll bars work, but no text is drawn at all.  I see lots of drawing artifacts, background images showing and painting issues.  Can anyone else verify this?

**Comment by pyscripter** [comment]
This is quite important.  There is still 12% of desktops using Windows 7.  DirectWrite is supposed to be supported on Windows 7.Are you able to debug on your Windows 7 machine.   It would be useful to see what fails.

**Comment by pyscripter** [comment]
Can you try the [Windows 7 Platform Update](https://www.microsoft.com/en-us/download/details.aspx?id=36805)

> The Platform Update for Windows 7 enables improved features and performance on Windows 7 SP1 and Windows Server 2008 R2 SP1. It includes updates to the following components: [Direct2D](http://msdn.microsoft.com/library/windows/desktop/dd370990(v=vs.85).aspx), [DirectWrite](http://msdn.microsoft.com/library/windows/desktop/dd368038(v=vs.85).aspx), [Direct3D](http://msdn.microsoft.com/library/windows/desktop/hh309466(v=vs.85).aspx), [Windows Imaging Component (WIC)](http://msdn.microsoft.com/library/windows/desktop/ee719902(v=vs.85).aspx), [Windows Advanced Rasterization Platform (WARP)](http://msdn.microsoft.com/library/gg615082(v=vs.85).aspx), [Windows Animation Manager (WAM)](http://msdn.microsoft.com/library/windows/desktop/dd371981(v=vs.85).aspx), [XPS Document API ](http://msdn.microsoft.com/library/windows/desktop/dd316976(v=vs.85).aspx), the [H.264 Video Decoder](http://msdn.microsoft.com/library/windows/desktop/dd797815(v=vs.85).aspx) and the [JPEG XR Codec](http://msdn.microsoft.com/library/windows/desktop/Hh707223(v=vs.85).aspx).

**Comment by MShark67** [comment]
I just installed the platform update and it didn't affect the issue at all.  I don't see any painting in the client area at all, except the caret and oddly enough selecting all text shows a blue 1-char wide block drawn for any lines that are empty.  Unfortunately I don't think I can do any debugging on the machine.

**Comment by pyscripter** [comment]
I am downloading a Windows 7 virtual machine to test, when I get some free time.

Debugging is going to be difficult.  Possibly with a logger.

**Comment by pyscripter** [comment]
There was another one in SynEditMiscClasses.  It now works!
Thanks for testing.

**Comment by MShark67** [comment]
Fixed!  Great job!  Thank you!

**Comment by maxkleiner** [comment]
Exe on Wine Debian Linux: 
I am getting an EOSError code by starting an EXE build with latest SynEdit and Delphi 11.3  with Wine: EOSerror SystemError code -2003283966 How can I find the reason why or the meaning of the code?
With the Delphi 10.4 Synedit getit packages it runs fine.
After debugg with dbg I suppose it has something to do with a lib of dwrite?
![VirtualBox_kalilinux64_22_11_2023_16_27_11error](https://github.com/TurboPack/SynEdit/assets/3393121/359ac0c7-48a9-416e-b5e1-c10dd4fc6f36)

![error_mintlinux2023-11-24](https://github.com/TurboPack/SynEdit/assets/3393121/317833c8-c511-4501-97c1-d697e9c25cc2)
![error_screen_8_win7](https://github.com/TurboPack/SynEdit/assets/3393121/2c242415-2226-4475-9a96-5710427bf369)
