### ISSUE TITLE
SynHighlighterSQL - DblClicking a word with special chars (non english) 

### ISSUE THREAD

**Issue by dados** [TurboPack/SynEdit#205]
Hi 

This has been a long time "bug" for me.

Without any highlighter it works fine
JAVA highlighter works fine also
I tested some other highlighters that fail this test: SQL, JSON, XML, PAS, PYTHON

I'm specially focused on the SynHighlighterSQL 

Test case:
New project, put SynEdit with SynHighlighterSQL component on a empty form and run the project.
Type in some word that contain non english characters for example:Á, Ä, É, Ð, Ö, Ð, Þ, Ú, Ý, Ø......
or using this random danish word: "æbletræ" -> apple tree
Try to double click on the center of the the word with the mouse.
The non english characters "æ" at the beginning and at the end are not included in the word selection.

Would it be possible to implement the same method as the Java highlighter uses like this ?

```
function TSynSQLSyn.IsIdentChar(AChar: WideChar): Boolean;
begin
  case AChar of
  //  'a'..'z', 'A'..'Z', '0'..'9', '_':    <-- remove this
  //    Result := True;               <-- remove this
    '-':
      Result := fDialect = sqlStandard;
    '#', '$':                          // TODO: check this case, ANSI code wasn't clear here if this is exclusively Oracle
      Result := fDialect in [sqlOracle, sqlNexus];
    '@':
      Result := fDialect in [sqlMSSQL7, sqlMSSQL2K];
     '!', '^', '{', '}','~':
      Result := fDialect = sqlNexus
    else
      Result := False;   <--- remove this
      Result := IsCharAlphaNumeric(AChar) or CharInSet(AChar, ['_', '$']);    <-- insert this
  end;
end;
```

or something even better :)

**Comment by pyscripter** [comment]
SynEdit now uses 
```
    Result := (AChar = '_') or  AChar.IsLetterOrDigit or
      CharInSet(AChar, FAdditionalIdentChars) and
      not IsWordBreakChar(AChar);
```

@MShark67 Could you please look into this and submit a PR.

**Comment by MShark67** [comment]
The SQL highlighter uses IsIdentChar in the parser to delimit keywords, which have a strict set of rules and it's called very very often.  I do have some concern that adding things to it may slow it down.

Would it make any sense to just change SynEdit's IsIdentChar to not use Highlighter.IsIdentChar? Something like:

```
function TCustomSynEdit.IsIdentChar(AChar: WideChar): Boolean;
begin
  if Assigned(Highlighter) then
    Result := (AChar = '_') or  AChar.IsLetterOrDigit or
      CharInSet(AChar, Highlighter.AdditionalIdentChars) and
      not Highlighter.IsWordBreakChar(AChar)
    // Result := Highlighter.IsIdentChar(AChar)
  else
    Result := (AChar = '_') or  AChar.IsLetterOrDigit or
      CharInSet(AChar, FAdditionalIdentChars) and
      not IsWordBreakChar(AChar);
end;
```
If not, let me know and I'll make the changes suggested above and do a pr.

**Comment by pyscripter** [comment]
The idea is that if a highlighter is attached, it is the job of the highlighter, which knows the rules of the language, to decide what is and what it isn't an IdentChar, WordBreakchar etc. 
Otherwise SynEdit provides a default behavior.

**Comment by dados** [comment]
>  I do have some concern that adding things to it may slow it down.

I agree wholehearted on the performance issue. 
But the editor must first and foremost work correctly (if we agree that this is not normal behavior)

**Comment by MShark67** [comment]
Dados, I think we all agree, and it will be fixed... it's just a question of the best way to handle this particular case.  I'll change the SQL highlighter to separate the two scenarios and we'll see how it goes.

**Comment by MShark67** [comment]
#206 Pr done!  Any comments welcome.  Pyscripter, thank you for that suggestion.

**Comment by dados** [comment]
Many thanks, excellent !
You guys rock 👍

**Comment by MShark67** [comment]
I just wanted to mention that I'm revisiting this particular issue as @pyscripter is correct (no surprise there lol!)  It does need to handle non-ascii characters even when just testing keywords, because I kind of forgot that user supplied tablenames can include non-ascii characters.  I was a bit surprised that Oracle allows them in unquoted identifiers in newer versions.  I'll be doing a pr soon with an improved version.
