### ISSUE TITLE
Latest SynEdit makes apps incompatible with Win XP/Vista due to DirectWrite

### ISSUE THREAD

**Issue by mitzix** [TurboPack/SynEdit#209]
Latest SynEdit makes apps incompatible with Win XP/Vista due to DirectWrite

**Comment by MShark67** [comment]
That's correct.  The amazing new features of the latest versions require DirectWrite and so are Windows 7 and up.  You can find the last GDI based version under releases, as well as a tag under that name.

**Comment by mitzix** [comment]
Windows Vista SP2 tested and it doesn't work.
