### ISSUE TITLE
TSynEdit control is invisible when compiled in Delphi 11 and run on Windows 7

### ISSUE THREAD

**Issue by MAVitecCito** [TurboPack/SynEdit#212]
Hi all.
I've upgraded to D11.1 and installed the latest TSynEdit VCL from 9. March 2022. If I create a new VCL project, put a TSynEdit on it and align it to the Top, the exe works fine on Windows 10, but on Windows 7 the whole control is totally transparent/invisible.
I've tried to fiddle with the Themes and Manifest settings in D11, but I cannot make it work on Windows 7.

Any ideas?

/Mikkel

**Comment by MShark67** [comment]
Take the latest version.  Pyscripter fixed that on March 14th.

**Comment by MAVitecCito** [comment]
Thank you. Any idea when it will become a part of the GetIt manager?
/Mikkel

**Comment by pyscripter** [comment]
Not sure.
