### ISSUE TITLE
TSynBaseCompletionProposalForm styling.

### ISSUE THREAD

**Issue by vincentparrett** [TurboPack/SynEdit#224]
TSynBaseCompletionProposalForm doesn't support vcl styles very well - and it looks pretty ugly (noting the comments in CreateParams about borders etc). 

My thoughts are to try and make it look something like the visual studio one, with a gripper in the bottom right corner to solve the resizing issue (noting that the VS one can only be resized by the gripper). 

![image](https://user-images.githubusercontent.com/1037262/182290930-e3e56f53-784b-41c6-838c-4ebbf72d8260.png)

I would probably need to create some small custom controls to make up the form rather than trying to do it all in the form class. 

Thoughts?

**Comment by vincentparrett** [comment]
Ok found a way to do it without creating separate components. I have it painting ok now (on w11 - stilll need to test on W10).

Question - anyone know why there are separate bitmaps for painting the title and the rows? They are both painted to the canvas each time anyway.. the titlebitmap seems to provide no benefit that I can see.

**Comment by pyscripter** [comment]
![image](https://user-images.githubusercontent.com/1311616/182367828-560f898e-c02b-49ea-8488-d5585cb1887c.png)

They look pretty good in PyScripter.  But any improvements are welcome.

The code in TSynBaseCompletionProposalForm is very old and I have not changed substantially.  So in relation to your question I am not sure.

**Comment by vincentparrett** [comment]
The thick border looks ugly to me. I managed to get a nice thin border that is resizable.  

Also investigating a bug where I eventually end up with a range check error. 

I'll submit a PR in the next day or so once I'm done.

**Comment by vincentparrett** [comment]
I have it painting nicely now, I was seeing flicker when scrolling the list before.  The range check error I was seeing was my fault so not an issue. 

I'm now looking at high dpi support.. the code is kindof a mess in this area I found that the proposal form is not scaling correctly - this may be a VCL bug as there are issues with dynamically created forms and the use of CreateNew. Also the way font scaling works is kinda funky. What isn't scaling at all is the ItemHeight - I will look at that today. 

96dpi
![image](https://user-images.githubusercontent.com/1037262/182963360-4e16eb91-fb1e-44d8-9e90-857094f778b7.png)

140 dpi

![image](https://user-images.githubusercontent.com/1037262/182963434-3217df25-21c8-4a4b-88c7-200583a5d047.png)

Anyway, taken way longer than I expected to get this far but hope to have a PR ready for review soon.

**Comment by vincentparrett** [comment]
Hmmm.. the 140 dpi image above looks blurry - but it's github doing that - it's not blurry in the screenshot I took or in the application!

**Comment by vincentparrett** [comment]
I have moved this PR to https://github.com/pyscripter/SynEdit - where I'll be contributing from now on
