### ISSUE TITLE
Porting to Lazarus (by myself, with your help sometimes)

### ISSUE THREAD

**Issue by mdbs99** [TurboPack/SynEdit#225]
I'm thinking to port this project to Lazarus, as PyScripter use this version. The default SynEdit in Lazarus is very different from this one and I guess that convert this project to compile in Lazarus could be less work than change PyScripter to use Lazarus SynEdit version.

If I start this work, would you like to receive PR's?

Thanks for your time.

**Comment by pyscripter** [comment]
That sounds good.   Once you got something working even with limited functionality then a merge will be considered.

**Comment by mdbs99** [comment]
My team wants to use PyScripter into Lazarus and I've suggested that SynEdit should be port first.
However Lazarus has a SynEdit package version (using the same TSynEdit name for the component, if you didn't know, but having a huge difference from TurboPack version) and as the IDE does not allow install two components with the same name into the pallete (AFAIK, Delphi behaves the same), we are rethinking if we change PyScripter to use Lazarus SynEdit or por TurboPack SynEdit to it.
If we choose the last one, I would be glad sending some PR's for you.

I will close this ticket for now and came back in the future. Thanks.
