### ISSUE TITLE
64bit - Component TSynCompletionProposal Crash (D 11.2)

### ISSUE THREAD

**Issue by jBitHub** [TurboPack/SynEdit#234]
Delphi 11.2
Simply drag the TSynCompletionProposal component onto an empty window. Compile the project as a 64bit application.
Access violation: ---------------------------
raised exception class EAccessViolation with message 'Access violation at address FFFFFFF2F80F84. Execution of address FFFFFFF2F80F84'.
---------------------------

**Comment by pyscripter** [comment]
This fork does not have the CreateWnd override, that I saw you mention in https://github.com/SynEdit/SynEdit/issues/194#issuecomment-1269980126.   I don't think this bug applies to this fork.   If you test  with this fork and you find a bug, please resubmit.

**Comment by jBitHub** [comment]
Thank you very much for the quick answer. I will have a look at it.
