### ISSUE TITLE
value of the SYNS_FriendlyAttrKey constant

### ISSUE THREAD

**Issue by Lajos-Juhasz** [TurboPack/SynEdit#240]
I'm using the FriendlyName of the attribute of highlighters to create an options dialog. As far as I can see everywhere SynEditStrConst.SYNS_FriendlyAttrKey is used for Keyword, but the value of the constant is Key this is not descriptive enough. Could the value be changed to be Keyword?

**Comment by pyscripter** [comment]
For keywords  SYNS_FriendlyAttrReservedWord is used.
'Key' (SYNS_FriendlyAttrKey) is used for key-value pairs as for example in INI files.

**Comment by Lajos-Juhasz** [comment]
Ok, I made an investigation the original code (years ago) was:

fKeyAttri := TSynHighlighterAttributes.Create(SYNS_AttrReservedWord, SYNS_FriendlyAttrReservedWord);

That is changed wrongly to:

fKeyAttri := TSynHighlighterAttributes.Create(SYNS_AttrKey, SYNS_FriendlyAttrKey);

**Comment by Lajos-Juhasz** [comment]
The problematic change is: https://github.com/SynEdit/SynEdit/issues/112

**Comment by pyscripter** [comment]
Fixed in https://github.com/pyscripter/SynEdit
