### ISSUE TITLE
Incorrect height of TSynCompletionProposal

### ISSUE THREAD

**Issue by mair0301** [TurboPack/SynEdit#33]
Hello, 
Thank you so much for trying to fix the problem. I’ve updated my SynEdit sources with your new version of the TSynCompletionProposal. But I’ve noticed that the main bug is still there. If the proposal appears and the user changes the size of it manually, the size of the proposal will be restored correctly, even after appearing multiple times. But if the user doesn’t change the size of it, the proposal popup will increase in height each time it is opened. It does so until the height of that proposal is as big as the size of the monitor. Even if the user changes the size manually, after restarting the app, the behavior is back to default, and the height increases as described each time the proposal is opened. 

I would be very grateful, when you try to fix this problem finally.  
Best greetings from Germany :)

**Comment by pyscripter** [comment]
Are you sure you are using the latest version???

**Comment by mair0301** [comment]
Oh yes,  

I really worked with the old version of your code. Now I really updated my SynEdit sources and there is another error. In our company we use Delphi Tokyo (Delphi 10.2) and I’ve noticed that our Delphi version does not support the function GetCurrentPPI. After research the internet how to fix the problem, I’ve figured out, that Delphi Sydney (Delphi 10.4) supports this function. So now my Delphi project is not compiling any more. 

It would be great if you could develop a solution that works for our Delphi version, too :)

**Comment by pyscripter** [comment]
TurboPack Synedit (as well as the other TurboPack repositories) aim to stay compatible with the latest version of Delphi.

Having said that I did add a compatibility fix, so the code should now compile with Delphi Tokyo and earlier versions (please check).  But do note that Per monitor DPI awareness would only work if you compile with Delphi Rio or higher.
