### ISSUE TITLE
Current code will not build in Delphi 10.2.3

### ISSUE THREAD

**Issue by wmeyer48** [TurboPack/SynEdit#38]
Cannot build in Delphi 10.2.3. Found that the issues is resolved with this change:
In SynEdit\Source\SynCompletionProposal.pas:
function GetCurrentPPI: Integer; **_{override;}_**
My searching shows that there is no ancestor to override.

**Comment by pyscripter** [comment]
The TurboPack repositories aim to support the latest versions of Delphi.  Please see the releases which contain SynEdit versions that work with earlier versions of Delphi.
