### ISSUE TITLE
Problem in TSynCssSyn with some CSS code

### ISSUE THREAD

**Issue by dec** [TurboPack/SynEdit#39]
Hello to all,

First of all, thanks very much for this SynEdit package for Delphi. I am using Delphi 10.4 and the latest version of this SynEdit package (version 1.5 / 21 Sep 2020) and found a problem while using the TSynCssSyn as the highlighter for SynEdit.

The problem causes that the app freezes without any kind of information nor error.

In order to reproduce the error, just place a SynEdit component in a TForm and set a TSynCssSyn highlighter for the SynEdit component. Then just try to copy this CSS code inside the SynEdit component:

`[class^="icon-"], [class*=" icon-"] {
}`

Since the above code freezes the app, I recommend you to compile an app and try it in that app, instead of in the Delphi IDE, because in this last case the Delphi IDE freezes too.

Thanks very much in advance for any kind of help.

**Comment by dec** [comment]
Hello to all,

Another way to reproduce the error, instead to copy the entire piece of CSS code that I mention before, we can just start to write this CSS code:

[class^

... before we can see the ^ character, the app freezes as mentioned.

**Comment by dec** [comment]
Hello to all,

To give more information, apparently this issue is related with this other from other SynEdit Github project:

https://github.com/SynEdit/SynEdit/issues/44

Certainly, I replace the "Source" folder from the referred project and that seems to solve the problem.

**Comment by pyscripter** [comment]
I have now synchronized the file with SynEdit/SynEdit.  Please check it works.

**Comment by dec** [comment]
Hello to all,

Thanks for your quick reply, @pyscripter! Yes; certainly that's works as expected now. :-)
