### ISSUE TITLE
[dcc32 Error] SynEditMiscClasses.pas(391): E2003 Undeclared identifier: 'WICBitmapInterpolationModeHighQualityCubic'

### ISSUE THREAD

**Issue by khongten001** [TurboPack/SynEdit#43]
The error appears when using delphi tokyo. Would you please fix? Thanks

**Comment by pyscripter** [comment]
High quality bitmap scaling was introduced in Delphi Rio.

The master branch aim to keep compatibility with the latest Delphi version.  You can use though the Tokyo release (under releases).

If you want to use the master branch you can replace ResizeBitmap in SynEditMiscClasses.pas with the following:

```
procedure ResizeBitmap(Bitmap: TBitmap; const NewWidth, NewHeight: integer);
var
  buffer: TBitmap;
begin
  buffer := TBitmap.Create;
  try
    buffer.SetSize(NewWidth, NewHeight);
    buffer.AlphaFormat := afDefined;
    buffer.Canvas.StretchDraw(Rect(0, 0, NewWidth, NewHeight), Bitmap);
    Bitmap.SetSize(NewWidth, NewHeight);
    Bitmap.Canvas.Draw(0, 0, buffer);
  finally
    buffer.Free;
  end;
end;
```
