### ISSUE TITLE
Could not find SynMemo.pas in the "Source" directory ?!

### ISSUE THREAD

**Issue by alperyazgan** [TurboPack/SynEdit#44]
Hi,

Package build (for RIO) needs  "SynMemo.pas" as found in the project file and it does not exists, I check the master branch could not find in this "TurboPack/SynEdit" project, is there any mixed/confused project files with any other SynEdit projects like "SynEdit/SynEdit" because that file exists in that project ??  
 
<DelphiCompile Include="..\..\..\Source\SynMemo.pas">

**Comment by alperyazgan** [comment]
I believe the project file is wrong, because ~2 years ago taht file should be removed from the project; can I correct the project file (RIO/CBuilder/SynEditCR.cbproj) and contribute to the project ?

**Comment by alperyazgan** [comment]
Same problem and fact with the file "SynRegExpr.pas"

**Comment by alperyazgan** [comment]
Corrected the problem, I can contribute If you let me ...

**Comment by pyscripter** [comment]
SynMemo has been removed from the project and the packages.

**Comment by pyscripter** [comment]
@alperyazgan Sure contributions are most welecome.   Please submit Pull Requests with your contributions.

**Comment by leus** [comment]
> SynMemo and SynRegExpr have been removed from the project and the packages.

Can I ask you why?

**Comment by pyscripter** [comment]
Delphi includes now a much better Regular Expression engine and is used instead and SynMemo served no purpose.  Just ise SynEdit instead,
