### ISSUE TITLE
Call for property "Lines" 's  Clear/Add/Append methods do not trigger OnChange event of TSynEdit

### ISSUE THREAD

**Issue by alperyazgan** [TurboPack/SynEdit#45]
Simply, a call for property "Lines"'s Clear/Append/Add method ( SynEdit->Lines->Clear(); ) does not trigger OnChange event of TSynEdit;

Is this expected behavior or a missed functionality ?

Thanks,  

Example : 

```
  SynEditCode->Lines->Clear();
  SynEditCode->Lines->Append(L"Something something");
```

**Comment by pyscripter** [comment]
I believe it is e.g.:

```pascal
function TSynEditStringList.Add(const S: string): integer;
begin
  BeginUpdate;
  Result := fCount;
  InsertItem(Result, S);
  if Assigned(OnInserted) then
    OnInserted(Self, Result, 1);
  EndUpdate;
end;
```

EndUpdate would result to a call to to the Change event unless you are within another BeginUpdate/EndUpdate block.  Look at TSynEditStringList.SetUpdateState and TStrings.BeginUpdate/EndUpdate.

**Comment by alperyazgan** [comment]
Yes, I am positive with the code that should trigger the event, but it really does not, I have checked my code against any lock as you suggested with the Begin/End Update block, but there is none.  

With TSynEditStringList
Add, AddStrings will trigger OnInserted
Clear will trigger fOnCleared <-- called not by OnCleared, by fOnCleared
Delete, DeleteLines will trigger fOnDeleted <-- called by not OnDeleted, by fOnDeleted

But the assigned events in the file "SynEdit.pas"  does not trigger OnChange event of TSynEdit itself  

```
constructor TCustomSynEdit.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  fLines := TSynEditStringList.Create(ExpandAtWideGlyphs);
  fOrigLines := fLines;
  with TSynEditStringList(fLines) do
  begin
    OnChange := LinesChanged; <-- Like this line
    OnChanging := LinesChanging;
    OnCleared := ListCleared;
    OnDeleted := ListDeleted;
    OnInserted := ListInserted;
    OnPutted := ListPutted;
  end;
```

As far as I can observe, if I am not omitting any,  I could not see any calling for OnChange event of TSynEdit itself  

```
procedure TCustomSynEdit.LinesChanged(Sender: TObject);
var
  vOldMode: TSynSelectionMode;
begin
//++ CodeFolding
  if (sfLinesChanging in fStateFlags) and fAllFoldRanges.StopScanning(fLines) then
  begin
    if Assigned(fHighlighter) and (fHighlighter is TSynCustomCodeFoldingHighlighter) then
      TSynCustomCodeFoldingHighlighter(fHighlighter).AdjustFoldRanges(AllFoldRanges,
      fLines);
    InvalidateGutter;
    Include(fStateFlags, sfScrollbarChanged);
  end;
//-- CodeFolding

  Exclude(fStateFlags, sfLinesChanging);
  if HandleAllocated then
  begin
//++ Flicker Reduction
//    UpdateScrollBars;
//-- Flicker Reduction
    vOldMode := fActiveSelectionMode;
    SetBlockBegin(CaretXY);
    fActiveSelectionMode := vOldMode;
    InvalidateRect(fInvalidateRect, False);
    FillChar(fInvalidateRect, SizeOf(TRect), 0);
    if fGutter.ShowLineNumbers and fGutter.AutoSize then
      fGutter.AutoSizeDigitCount(Lines.Count);
    if not (eoScrollPastEof in Options) then
      TopLine := TopLine;
  end;
end;
```

**Comment by pyscripter** [comment]
Yes you are right.  The Synedit OnChange event is triggered by DoChange which is linked to Unde/Redo.

This has always been like this in the original SynEdit, so I assume it is by design.   So for example that when you load a file, the OnChange event is not triggered, but when the user starts making changes you will be receiving OnChange notififications.  When you programmatically make changes, typically you would like those changes, to  be undoable.  If for instance you want to clear all lines, you should not use `SynEdit.Lines.Clear`, but` SelAll;  Sel := '';`  and now the changes are undoable and the Change event is triggered.

Of course the DoChange call can be moved to LinesChanged, so you will the same OnChange notificatios as LinesChanged.   This would be quite a major change, potentially breaking some of the existing Synedit code, so, although the change sounds reasonable, I am not sure it is advisable to do it.

**Comment by alperyazgan** [comment]
Thanks, I will accept it as by design.
I think, at least for now it should not be disturbed. Undo/Redo system will need "lots of" revisions/changes, possibly a new approach and design.  

Kind Regards,

**Comment by pyscripter** [comment]
The change is quite trivial to make and has not impact on Undo/Redo.  When I was referring to a "major breaking change", I meant the way users used to respond to SynEdit.OnChange messages.  With the change they would receive them at different times, when opening a file for instance.

I may still move DoChange to LinesChanged.  I just need to think a bit about the implications.

**Comment by pyscripter** [comment]
I decided that it makes more sense to unlink DoChange from undo/redo and call it from LinesChanged instead.  So whenever the text bufffer changes the event is triggered.  Also when multiple changes to the buffer are made with the Lines.BeginUpdate Lines.Endupdate, only one Change even is fired.
