### ISSUE TITLE
DragDrop editing - COPYMODE

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#46]
Hello
Drag/Drop of selected text with CTRL doesn't work
for Drag editing COPY mode everything is prepared, only the CTRL is necessary to add into Shift check

procedure TCustomSynEdit.MouseDown(Button: TMouseButton; Shift: TShiftState;
change:
  if (Button = mbLeft) and ((Shift + [ssDouble]) = [ssLeft, ssDouble]) then
to
  if (Button = mbLeft) and ((Shift + [ssDouble]) = [ssLeft, **ssCtrl**, ssDouble]) then

**Comment by pyscripter** [comment]
It works here fine.  Are you sure you are using the latest version from this repository?

**Comment by JaFi-cz** [comment]
Yes, I use.
Are you sure it works with CTRL as drag copy, not drag move only?
When I keep CTRL and try to drag selected block, it start new selection, not drag

**Comment by pyscripter** [comment]
The way this works now is that you start the drag without the Ctrl key and then, at any time before drop, you press the Ctrl key,

**Comment by JaFi-cz** [comment]
The way you described - press CTRL before you stop drag isn't standard behavior as it's confusing for users.

Standard behavior:
select block
press CTRL and start drag it. It should COPY block on place where you stop drag. 
When you do it now, it starts new block selection

The modification is very easy, include ssCtrl into Shift check as I mentioned before.

I have no problem, let is as it is, I will keep my copy of Synedit as I did over 20 years  ;-)

**Comment by pyscripter** [comment]
Please test and confirm the fix.

**Comment by JaFi-cz** [comment]
Tested and confirmed correct behavior. Thank you
