### ISSUE TITLE
Char #0 in file causes infinite loop when loading

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#50]
When file contains char #0 it casues infinite loop, generate milions of empty lines and ends with end of memory exception

Unit SyneditTextBuffer
procedure TSynEditStringList.SetTextAndFileFormat
problematic code is on the line 877:

```
        while not (Ord(P^) in [0, $A, $D]) and (P^ <> WideLineSeparator) do
        begin
          Inc(P);
        end;
```

It never increase "P" and caused infinite loop

**Suggestion:**
exclude #0 char from the file content
another solution: replace #0 for space

**Comment by pyscripter** [comment]
Please check and confirm.

**Comment by JaFi-cz** [comment]
Checked and confirmed
