### ISSUE TITLE
Synedit - TCustomSynedit.Destroy

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#52]
Hello
Is there any reason why **inherited Destroy** call is somewhere in the begining of Destroy method? In my opinion, I would move it to the end of TCustomSynedit.Destroy

The second thing in the Destroy
Quite often I get access violation from destroying Synedit component caused by releasing CodeFolding. 
Maybe it's caused by MultiHighlighter, where some highlighters are codefolding ready (PHP) and some not.

Suggestion:
on the end of TCustomSynedit.Destroy change releasing of code folding part to:
```
//++ CodeFolding
  if fCodeFolding <> nil then fCodeFolding.Free;   
  if fAllFoldRanges <> nil then fAllFoldRanges.Free;
//-- CodeFolding
```
it looks like it helps and it doesn't cause any problems.

**Comment by pyscripter** [comment]
```pascal
  if fCodeFolding <> nil then fCodeFolding.Free;   
  if fAllFoldRanges <> nil then fAllFoldRanges.Free;
```

is exactly equivalent to

```pascal
  fCodeFolding.Free;   
  fAllFoldRanges.Free;
```

Free checks for nil anyway,  The check for nil is redundant.

**Comment by JaFi-cz** [comment]
I know, but it's a magic. 
This additional check prevents access violation problems at least for me. 

What about the inherit destroy? Is there any reason, why iit's on the begin of TSustomSynedit.Destroy and not on the end?

**Comment by pyscripter** [comment]
It shouldn't make a difference, but I moved it to the end anyway.
