### ISSUE TITLE
Replace with new lines - fix (pull request)

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#57]
New pull request was created. Problem was in encoding - you use UTF-8 BOM for source, I had ANSI

**Comment by pyscripter** [comment]
When new lines appear in replace expression, there is necessary to move pointer in result.
Test source:
XC_VAR01 , XC_MA_P01
XC_VAR02 , XC_MA_P01
XC_VAR03 , XC_MA_P02
XC_VAR04 , XC_MA_P03

Search: ^(XC_\w+)\s*,\s*(XC_\w+)\s*$
Replace: find(\n\tVin : $1\n\tVout : $2\n );\n
