### ISSUE TITLE
SeyneditRegExpSearch.pas - empty patterns usage

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#58]
As default is there set option **roNotEmpty**. It disallows you use regular expression to put char on the begin or end of each line. When you remove this option, it has no influence of functionality, but allows you to use "empty" patterns

Example text:
```
aa

aa

```

Search: ^
Replace: {

**Comment by pyscripter** [comment]
Could you please provide some more explanations.  What is the expected outcome and what is the actual?

**Comment by JaFi-cz** [comment]
Current situation, when roNotEmpty is included in default and you have no possibility to remove it leads to "wrong regular expression" message when you try to search for ^ or $ only. It disallows you insert content of the replace expression on any lines start or end.
Try my example with current Synedit version, remove roNotEmpty option (it's on 3 places in SynEditRegExpSearch.pas unit) and try it again. You will see the difference.

The change I suggest is remove roNotEmpty option, cause it's automatically added to any options you use.

**Comment by pyscripter** [comment]
I see...

> cause it's automatically added to any options you use.
How do you conclude that?

**Comment by JaFi-cz** [comment]
```
procedure TSynEditRegexSearch.SetOptions(const Value: TSynSearchOptions);
begin
  if ssoMatchCase in Value then
    fOptions := [roNotEmpty]
  else
    fOptions := [roNotEmpty, roIgnoreCase];
  RegEx := TRegEx.Create(fPattern, fOptions);
  RegEx.SetAdditionalPCREOptions(PCRE_UCP);
end;
```

**Comment by pyscripter** [comment]
Just to make sure.  Are you suggesting that we remove reNotEmpty from the constructor only and keeping it in SetOptions?

**Comment by JaFi-cz** [comment]
No, I mean remove it from constructor and set options. It has no influence of search.
Az alternative you can make it optional, but it means add property

**Comment by pyscripter** [comment]
But if I remove it from SetOptions it will never be set and empty matches could always happen.

**Comment by JaFi-cz** [comment]
This is what I wrote as alternative solution - make it optional (add property) in RegExp Synedit engine 
Empty expression were there in the past before Delphi reg exp engine in Synedit.

**Comment by pyscripter** [comment]
> Empty expression were there in the past before Delphi reg exp engine in Synedit
I could not find such an option in https://github.com/SynEdit/SynEdit/.

**Comment by pyscripter** [comment]
I committed anyway since your use case is common.
We should rethink how to expose roNotEmpty and other PCRE options to TSynEditRegexSearch.

**Comment by JaFi-cz** [comment]
Yes, in old implementation was no such options, but behavior was as I described
