### ISSUE TITLE
SQL Highlighter for Mysql

### ISSUE THREAD

**Issue by jcmontherock** [TurboPack/SynEdit#6]
Hello,
Thanks a lot for your work with SynEdit. It's awesome !
1) I was looking for an example of highlighter for writing a sql parser, but I didn't find any lexer in your source dir. 
2) I noticed that in the sql highlighter the char "#" is not considered as comment but as "unknown". Could you send me the sql lexer as an example for me ? 
See: https://dev.mysql.com/doc/refman/5.7/en/comments.html
Thanks in advance.

**Comment by pyscripter** [comment]
The SQL Highligihter  is here  https://github.com/pyscripter/SynEdit-2/raw/master/Source/SynHighlighterSQL.pas.  Feel free to submit Pull Requests implementing bug fixes or improvements.
