### ISSUE TITLE
Highlighters with list of keywords, e.g. UnixShellScript

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#61]
Hello
you replace keyword definition in SynHighlighterXXX from **array of UnicodeString** to **array of string**, but you let WideCompareText()/WideCompareStr() in IsKeyword() function

In my country and other slavic countries is "ch" taken as one char and alphabetically is placed behind the "h" char in ANSI rules for sorting and comparing.
It means when you have string sorted, order isn't 
c, ca, ... cg, ch, ci, ... d
but "ch" is behind the "h" char

The problem is caused by **array of string** vs **WideCompareStr()** in IsKeyword() function
Solution for correct string handling is:
array of UnicodeString + WideCompareStr()
or
array of string + CompareStr() 

See the attached acreenshot, it's copy of keywords from SynHighlighterUnixShellScript.pas and highlighted in Unix shell script highlighter:
[Screenshot](https://ctrlv.link/shots/2021/06/01/hZxd.png)

**Comment by pyscripter** [comment]
Not sure I follow.  UnicodeString and string are the same in Delphi.

**Comment by JaFi-cz** [comment]
If it is same, there wouldn't be different behavior.
When unicode string + WideCompareStr, all keywords are recognized with current order
When string + WideCompareStr, keywords starting to "ch" like chmod are not recognized if I don't move them behing the "g" keywords, but it isn't solution (see the screenshot in previous add)
When string + CompareStr(), all keywords are recognized with current order.

Maybe there is different default code page between str and unicodestr. 

If you insist that unicodestring and string is the same, why is in System.pas used unicodestring but not string in functions like UTF8Encode, UTF8Decode, StringToOleStr, 

Solution is simple. If you insist on "string", you have to change WideCopareStr() to CompareStr() at least in the IsKeyword() functions.

**Comment by pyscripter** [comment]
string is the same as Unicode string.  See for instance:
http://docwiki.embarcadero.com/Libraries/Sydney/en/System.UnicodeString

> Delphi also supports UnicodeString, but implements it as a primitive type rather than a class. By default, variables declared as type String are UnicodeString.

These WideCompareStr and other Wide...  functions are a leftover from the past and need to be removed.   The question is should they be replaced with AnsiCompareStr or CompareStr.  The former does a system based unicode comparison and the latter just compares the Ord(ch).  From what you say CompareStr should be used since the Unicode comparison may create problems in certain locales and keywords are typically ascii strings.

**Comment by JaFi-cz** [comment]
Usage of AnsiCompareStr for string will generate warnings, so CompareStr() will be better, especially for keywords, where should be basic chars only.

I understand  your point about string and unicodestring. But usage string/unicodestring variable declaration causes different program behavior and this is more important for me than description in embarcadero wiki. I can't argue with users, that program works OK cause embarcadero write it in documentation when program doesn't work correctly.

**Comment by JaFi-cz** [comment]
Sorry, you are right with AnsiCompareStr(). I am switching between D7 (not for Synedit) and D10.4.2
For clarification, let's make:

```
var
  sch, sci: string;
begin
  sch := 'ch';
  sci := 'ci';

  sch > sci = False;
  CompareStr(sch, sci) > 0 = False;
  WideCompareStr(sch, sci) > 0 = True;
  AnsiCompareStr(sch, sci) > 0 = True;
```

As you can see AnsiCompareStr() is equivalent of WideCompareStr() and doesn't solve problem.
