### ISSUE TITLE
Cursor manipulation and selection

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#62]
This version of Synedit is broken. I don't know from which version it comes, but it contains basic bugs what didn't exist in many years old version

Few examples:
1. put cursor somewhere in the middle of line and type few letters. Press SHIFT and start selection. Selection starts from the position where cursor was before typing. There is necessary to update FBlockStart and FBlockEnd on end of ecChar command

2.  Line selection and deleting
take file with few lines
put cursor on the begin of line
press Shift+Down to select line
press DEL to delete line
press Shift+Down to select line - nothing happen, cause again FBlockBegin and FBlockEnd position isn't updated

It really needs revision of basic functionality

**Comment by JaFi-cz** [comment]
Another place, where BlockBegin/BlockEnd isn't updated and point to some past position: Editor.SelText := '';

**Comment by pyscripter** [comment]
I cannot reproduce any of the bugs you describe.   Are you sure you are using the version in this repository?

**Comment by JaFi-cz** [comment]
At finally, it was my fault, but on the other side...

Take this code and put it into new empty project into FormCreate and test selection:
```
  with TPSSynedit.Create(self) do
  begin
    Parent := Self;
    Align := alClient;
    Highlighter := TSynUNIXShellScriptSyn.Create(Self);
    BeginUpdate;
    Text := 'Put cursor here | with mouse, write few letters and pres Shift+Right';
    // End update without begin update
    Lines.EndUpdate;  // This line causes problems
    EndUpdate;
  end;
```

System.Classes Lines.EndUpdate implementation:
In my opinion, it isn't lucky implementation. You shouldn't reach negative FUpdateCount. Negative FUpdateCount should reset it.
```
procedure TStrings.EndUpdate;
begin
  Dec(FUpdateCount);
  if FUpdateCount = 0 then SetUpdateState(False);
end;
```

So we can close it.
