### ISSUE TITLE
Support HTML copy and paste

### ISSUE THREAD

**Issue by pyscripter** [TurboPack/SynEdit#65]
As per title.
Add the HTML clipboard format to the SynEdit DataObject.

**Comment by pyscripter** [comment]
Pasting cod into PowerPoint:
![image](https://user-images.githubusercontent.com/1311616/120893063-d847d380-c619-11eb-8a66-525927f60772.png)

**Comment by JaFi-cz** [comment]
This modification broke Copy/Paste in plaintext without highlighter.

Simulation:
Create new empty project with Empty synedit without highlighter.
write something, try to copy/paste

**Comment by pyscripter** [comment]
Thanks, I will fix it.
