### ISSUE TITLE
Autoindent with Smarttabs bug in case of mix of realtabs and spaces

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#67]
Issue related to pool request  #66 

If code contains combination of real tabs and spaces and both Autoindent and SmartTabs are on, Synedit causes wrong behavior.
This modification switches off Smarttabs for Autoindent action and in case eoTabsTo Spaces is ON it puts spaces instead of the tabs.
The problem is caused by DoTabKey procedure in case SmartTabs are on. 

To demonstrate current bug, create new empty VCL project, add Synedit, SynEditKeyCmds into uses and paste following code into FormCreate and simple press Enter on the end of second line. 
There are 2 bug cases, one for RealTabs, second for Spaces - both settings causes wrong behavior.

```
  with TPSSynedit.Create(self) do
  begin
    Parent := Self;
    Align := alClient;
    WantTabs := True;
    { real tabs bug example. For spaces mode bug example set condition to false }
    if True then
      Options := Options - [eoTabsToSpaces]
    else
      Options := Options + [eoTabsToSpaces];

    Options := Options + [eoAutoIndent, eoSmartTabs, eoSmartTabDelete, eoShowSpecialChars];
    TabWidth := 8;
    Text := 'a'#9'b'#9'c1'#13#9#9'c2';
    CaretY := 2;
    CommandProcessor(ecLineEnd, #0, nil);
    { you should stay on the end of second line, press Enter.
      - for Realtab mode 2 additional spaces are added
      - for spaces wrong number of spaces is added }
  end;
```

**Comment by pyscripter** [comment]
Fixed with #66
