### ISSUE TITLE
COPY / paste bloken by modification in #65

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#69]
#65  modification broken Copy/Paste in Synedit without highlighter.

Simulation is simple - paste synedit component, don't assign highlighter, write anything and test copy/paste

To fix it is necessary to don't export into HTML when no highlighter is assigned (or anything more complicated)

SyneditDataObject.pas, line 145
constructor TSynEditDataObject.Create(ASynEdit : TObject);
....

```
  if (ASynedit as TCustomSynedit).Highlighter <> nil then
    StreamHtml(ASynEdit, HtmlStream);
```

**Comment by pyscripter** [comment]
Thanks, I will fix it soon.

**Comment by pyscripter** [comment]
@JaFi-cz Could you please confirm it is fixed?

**Comment by JaFi-cz** [comment]
Confirmed. Problem is fixed
