### ISSUE TITLE
Copy to clipboard in HTML format

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#70]
I got complains from users that copy to clipboard from SynEdit contains formated text and this format is preferred by application you paste it.

Are you against it to make it optional? Some like eoHTMLFormatInCopy what will be ON by default with possibility to switch off HTML format as part of the copy to clipboard?

**Comment by pyscripter** [comment]
This is how OLE copy and paste works.  Say you copy SynEdit text to Powerpoint.  Powerpoint sees both formats and decides which one to use.  If you want plain text, Powerpoint allows you to either select this format before (Paste Special) or after paste.

**Comment by JaFi-cz** [comment]
I know and understand it. But some application doesn't allows you to paste with selection.
If you don't think the option has sense and you want to force HTML 
Never mind. I will disable it in my version in SynEditDataObject.
I allows to users copy into RTF, HTML and TeX if they want it. But in most cases they need to copy plain text only.

**Comment by JaFi-cz** [comment]
Synedit without highlighter, write any two lines, select and copy
Try to paste to Excel - you get message: Excel can't paste data

Usual usage is create tab delimiter data and paste it into Excel. It worked OK before "OLE paste" Synedit feature was introduced. I still don't find it as usefull as you mean.
For plain text it should work without necessary to use paste special / as text in Excel. 

I request again possibility to switch off OleDrop and give possibility to paste it by old way. Or fix OLE clipboard data handling.

**Comment by pyscripter** [comment]
I will look into it.

**Comment by JaFi-cz** [comment]
What about this issue? Elegant solution can be keep both Copy methods and drive it with Synedit options. 
User can choose what he prefer - possibility to copy formated text or possibility to work with data.

**Comment by pyscripter** [comment]
Yes sorry.  I need to get back to it.

**Comment by JaFi-cz** [comment]
If you agree with "option" solution, I can prepare it.

**Comment by pyscripter** [comment]
I was thinking of adding an overload of CopyToClipboard e.g.
procedure CopyToClipboard(ClipFormats:  array of Cardinal);

Maybe then you could then add support for other formats to the SynEditDataObject.

The questions are:
- What the formats should be when you execute CopyToClipboard without parameters
- What the formats should be when you drag and drop text.

**Comment by JaFi-cz** [comment]
Problem with Excel is, that Excel prioritize formated text.
If you send plain text + formated text, Excell will paste formated text.

I am not sure if overloaded procedure helps. Most of operations is done by calling editor command ecCopy

**Comment by JaFi-cz** [comment]
I though about it. Just now we have DoCopyToClipboard() procedure what is called from all cases (Copy, Cut)...
We can Add another parameter, something like:
`DoCopyToClipboard(const SText: string; APlainText: boolean = False);`
and split content to 2 procedures called from DoCopyToClipboard():
```
DoCopyToClipboardPlainText(const SText: string);
DoCopyToClipboardFormatted(const SText: string);
```
With option what set default Cut/Copy behavior it won't break current usage and it will give you possibility to call it from code as you need.
With adding commands:
```
ecCopyFormated
ecCopyPlainText
ecCutFormated
ecCutPlainText
```
It gives you possibility to assign shortcuts and user can configure it he needs.

**Comment by pyscripter** [comment]
I ended up adding a new option eoCopyPlainText.

**Comment by JaFi-cz** [comment]
Thank you, it's absolutely enough for me.

**Comment by JaFi-cz** [comment]
But. I see you didn't test it.
With SyneditDataObject the **paste into Excel is completely broken** even you disable HTML format.

Test:
one[tab]two[tab]three
one[tab]two[tab]three

copy to clipboard and paste into Excel
You will get error message: Excel can't paste data
The only solution is forget DataObject and make it by old way.

**Comment by JaFi-cz** [comment]
It works now, thank you.

**Comment by pyscripter** [comment]
I have made some changes.  Worth checking again.  Thanks.

**Comment by JaFi-cz** [comment]
Checked and it works as expected. Thank you.
