### ISSUE TITLE
Wordwrap glyph is not transparent and always drawn with a green background

### ISSUE THREAD

**Issue by jonjbar** [TurboPack/SynEdit#75]
Default Worwrap glyph is always drawn with a green background instead of being transparent.
Forcing `fGutter.Gradient` to true doesn't seem to resolve this problem despite what the code says:
`// draw word wrap glyphs transparently over gradient`

**Comment by jonjbar** [comment]
I found out that it only happens if you change the project's manifest to "System Aware", "Per Monitor" or "Per Monitor v2".

**Comment by pyscripter** [comment]
Could you please test the fix?
