### ISSUE TITLE
Problems with selection after typing and Enter on second to last character of line.

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#83]
This particular issue appears to have started in commit bdbcebb titled Fix #78 New undo/redo system.

Item 1: Selecting text with keyboard after typing characters.
  Type any string and then Shift-RightArrow to begin selecting text.
  Expected:  that selection will start at the current caret position.
  Observed:  Selection seems to begin at the beginning of the string just typed (it's a bit variable depending on how you do this test.)

Item 2:  Hitting the Enter key on the second to last character in a line.
  Expected:  That an enter will be inserted at the current position, moving the last character to the next line
  Observed:  The final character remains on the current line and the caret moves to the new line.

I hope those make sense and can be reproduced. Let me know if you need clarification.

-Mark

**Comment by MShark67** [comment]
For item 1 it seems like uncommenting the SetBlockBegin(CaretXY); line in TCustomSynEdit.LinesChanged seems to fix it.

**Comment by pyscripter** [comment]
Yes this is my fix for the second.

But I want to avoid the first.  It interferes with the restoration of selection during undo and it is not needed.  I am checking alternative fixes and will be releasing an update soon.

**Comment by pyscripter** [comment]
Please do check the the errors are fixed.
Thanks for finding the errors and keep trying to find more!
