### ISSUE TITLE
Minor issue in TCustomSynEdit.ExecCmdCaseChange

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#88]
Issue:  The various case changing commands exit early if the caret is at the end of a word.

Fix:
procedure TCustomSynEdit.ExecCmdCaseChange has check:
`
  if ReadOnly or (GetWordAtRowCol(CaretXY) = '') then Exit;
`
should just be:
`
  if ReadOnly then Exit;
`

-Mark

**Comment by pyscripter** [comment]
Related to #53
What is your view?

**Comment by MShark67** [comment]
I do think #51 is a good change, however I'd still remove the GetWord check OR add a check for SelAvail in the "if" above.   Mainly the issue is that you could select some text with trailing whitespace such that the caret is between two whitespace chars.  You'd still want to do the case change, even though the caret isn't on a word.
