### ISSUE TITLE
Setting the Text property and Undo

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#98]
This could be an intended change, but setting .Text adds each line of the text individually to the undo buffer.  Previously I believe it either grouped the undo into a single operation or cleared/didn't set the undo for this at all.  I'm not sure what the fix (if any) should be, but perhaps grouping it as one undo operation would be the most flexible option.

**Comment by pyscripter** [comment]
Normally you clear the Undo after loading a file or setting the SynEdit Text property.
You could surround the assignment to the Text property with Begin/End UndoBlock.
In any case I am providing a more general fix.

**Comment by MShark67** [comment]
Thanks!  I think it's a good change.  And agreed on clearing undo after loading and also using begin/end undoblock where needed.
