### ISSUE TITLE
SpellCheck fixes and improvements

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#99]
Fixed cyrilic dictionary support
Better and more correct word suggestion
Get rid of different form of xxxUpper/xxxLower case

pull request created

**Comment by pyscripter** [comment]
I have merged this but just an idea 

why don't you change:
FCacheArray: array[0..65535] of array[0..1] of Cardinal;

to 
FCacheArray: TList<TPair<Cardinal>>
or
FCacheArray: TList<array[0..1] of Cardinal>;  (you may have to create a type for array[0..1] of Cardinal)
or a dynamic array, but then you have to manage size.
FCacheArray: array of array[0..1] of Cardinal;

to optimize memory usage?
